apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}
rules:
- apiGroups: [""]
  resources:
  - namespaces
  verbs: ["get", "watch", "list","update", "patch"]
